### ISSUE TITLE
Vote top and wallsign error

### ISSUE THREAD

**Issue by yaitsbilly** [teozfrank/UltimateVotes#31]
Having two issues, first is /uv setwallsigns gives error below and second is /vote top just say "Votes have not been loaded! or no Votes exist ot load!" I have MySQL setup and can see tables with data. And I've set "loadonstartup: true".

[22:36:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'uv' in plugin UltimateVotes v1.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot.jar:git-Spigot-56f8471-43183ea]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot.jar:git-Spigot-56f8471-43183ea]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.WorldEditPlugin.getSelection(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/bukkit/selections/Selection;
        at teozfrank.ultimatevotes.util.c.a(FileManager.java:322) ~[?:?]
        at teozfrank.ultimatevotes.a.d.onCommand(UltimateVotesListener.java:76) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Spigot-56f8471-43183ea]
        ... 17 more

**Comment by teozfrank** [comment]
Hey, You need the updated version that is compatible with the latest worldedit. Have you joined the discord server? Once you have gotten verified you will have access to a beta build which has this fixed. 

https://discord.gg/hn8e9tu
