### ISSUE TITLE
Plugin does not give informative exception messages.

### ISSUE THREAD

**Issue by SenseiKiwi** [teozfrank/UltimateVotes#32]
As it says in the title. Either the guide for setting up the plugin should clearly state that the database has to be created ahead for the plugin to work, or the plugin should handle the creation process. It's not obvious that the plugin won't do it. This is non-trivial for your average user who has no knowledge of these things and has to follow step-by-step guides. It doesn't help that the plugin shows a generic connection error if the database doesn't exist.

This cost me several hours of checking and rechecking a database setup and ended with me taking the plugin apart and stepping through to figure out what the actual error was. There are likely others who've had this issue and gave up. It would be easy to prevent.

**Comment by teozfrank** [comment]
The plugin cannot create the database, when you enter your database details you provide the name of the database you have access to. The tables are then automatically created if they do not exist. I can update the documentation to reflect this if you feel its not clear. The generic error comes from trying to connect to the database, I have no control over it. Can you be more specific on what error or provide some logs of the errors that caused you confusion?

**Comment by SenseiKiwi** [comment]
The exception I was seeing was this:
```
16.02 02:08:18 [Server] INFO [UltimateVotesBungee] [Warning] DatabaseManager could not establish a connection when trying to setup the connection!com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
16.02 02:08:18 [Server] INFO [UltimateVotesBungee] [Info] Attempting to connect to MySQL database.
16.02 02:08:22 [Server] INFO [UltimateVotesBungee] [Warning] DatabaseManager could not establish a connection when trying to setup the connection!com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
16.02 02:08:22 [Server] SEVERE java.lang.NullPointerException
16.02 02:08:22 [Server] SEVERE at com.teozcommunity.teozfrank.ultimatevotesbungee.util.b.d(DatabaseManager.java:183)
16.02 02:08:22 [Server] SEVERE at com.teozcommunity.teozfrank.ultimatevotesbungee.util.b$1.run(DatabaseManager.java:33)
...
```

Unfortunately, either the underlying error (the database not existing) gets swallowed somewhere, or it's never indicated. I used MysqlDataSource to get a connection in a small test program and it gave a more descriptive exception:

```
import java.sql.*;
import com.mysql.jdbc.jdbc2.optional.*;

public class Test {

     public static void main(String[] args) throws Exception {
          MysqlDataSource dataSource = new MysqlDataSource();
          dataSource.setUser("cooluser");
          dataSource.setPassword("BlahBlahBlah");
          dataSource.setServerName("localhost");
          dataSource.setUseSSL(false);
          dataSource.setDatabaseName("ultimatevotes");
          Connection conn = dataSource.getConnection();
          conn.close();
     }
}
```

The exception was...
```
Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'ultimatevotes'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
...
        at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107)
        at Test.main(Test.java:13)
```

One solution is for the setup guide to highlight that the database must be created ahead - that installing and configuring MySQL is not enough. This contradicts my experience that tools create the databases they need out of the box so that users don't have to worry about their internals. I was surprised at having to create the DB for UV to populate it. A corresponding error would make it easier to diagnose this issue if someone shows up saying "it doesn't work!!!1!".

Another solution would be to have UV create the DB. I believe JDBC allows you to do this with the _createDatabaseIfNotExist_ property. Of course, that assumes the account has the necessary permissions and could lead to similar mystery errors if the DB doesn't exist and the permissions aren't right. Alternatively, you could provide a separate tool or script that does the initial DB creation, separate from the plugin. A separate tool gives finer control and may make reporting errors easier.

As developers, this is trivial stuff once we know what's going on, but it's a nightmare for regular folks.

**Comment by teozfrank** [comment]
Good points, as long as the documentation is clearer im sure that will cover it. Maybe if we look at the inner exceptions it might give more information than failed to connect to database as it is quite generic alright.

In the example code you do not have any exception handling, the plugin does but it might be catching the error at the highest level and not the inner exceptions. I will look into better error handling.

**Comment by teozfrank** [comment]
> 
> 
> The exception I was seeing was this:
> 
> ```
> 16.02 02:08:18 [Server] INFO [UltimateVotesBungee] [Warning] DatabaseManager could not establish a connection when trying to setup the connection!com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 16.02 02:08:18 [Server] INFO [UltimateVotesBungee] [Info] Attempting to connect to MySQL database.
> 16.02 02:08:22 [Server] INFO [UltimateVotesBungee] [Warning] DatabaseManager could not establish a connection when trying to setup the connection!com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
> 16.02 02:08:22 [Server] SEVERE java.lang.NullPointerException
> 16.02 02:08:22 [Server] SEVERE at com.teozcommunity.teozfrank.ultimatevotesbungee.util.b.d(DatabaseManager.java:183)
> 16.02 02:08:22 [Server] SEVERE at com.teozcommunity.teozfrank.ultimatevotesbungee.util.b$1.run(DatabaseManager.java:33)
> ...
> ```
> 
> Unfortunately, either the underlying error (the database not existing) gets swallowed somewhere, or it's never indicated. I used MysqlDataSource to get a connection in a small test program and it gave a more descriptive exception:
> 
> ```
> import java.sql.*;
> import com.mysql.jdbc.jdbc2.optional.*;
> 
> public class Test {
> 
>      public static void main(String[] args) throws Exception {
>           MysqlDataSource dataSource = new MysqlDataSource();
>           dataSource.setUser("cooluser");
>           dataSource.setPassword("BlahBlahBlah");
>           dataSource.setServerName("localhost");
>           dataSource.setUseSSL(false);
>           dataSource.setDatabaseName("ultimatevotes");
>           Connection conn = dataSource.getConnection();
>           conn.close();
>      }
> }
> ```
> 
> The exception was...
> 
> ```
> Exception in thread "main" com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'ultimatevotes'
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
> ...
>         at com.mysql.jdbc.jdbc2.optional.MysqlDataSource.getConnection(MysqlDataSource.java:107)
>         at Test.main(Test.java:13)
> ```
> 
> One solution is for the setup guide to highlight that the database must be created ahead - that installing and configuring MySQL is not enough. This contradicts my experience that tools create the databases they need out of the box so that users don't have to worry about their internals. I was surprised at having to create the DB for UV to populate it. A corresponding error would make it easier to diagnose this issue if someone shows up saying "it doesn't work!!!1!".
> 
> Another solution would be to have UV create the DB. I believe JDBC allows you to do this with the _createDatabaseIfNotExist_ property. Of course, that assumes the account has the necessary permissions and could lead to similar mystery errors if the DB doesn't exist and the permissions aren't right. Alternatively, you could provide a separate tool or script that does the initial DB creation, separate from the plugin. A separate tool gives finer control and may make reporting errors easier.
> 
> As developers, this is trivial stuff once we know what's going on, but it's a nightmare for regular folks.

Just looking a bit more into this, you are using a different set of libraries and under the set that I am using. Noteably I am using DriverManager.getConnection(String url, String username, String password) to get a SQL connection in the plugin and it simply will not provide the detail that the example you provided. Error message is always "Could not create connection to database server. Attempted reconnect 3 times. Giving up." even if you put in the wrong password or try to connect to an incorrect database. Any suggestions to change this to something else I may consider as long as it does not cause any backwards compatability as the current implementation works with all servers up to 1.15.2.
